### ISSUE TITLE
how to reset the interval time?

### ISSUE THREAD

**Issue by rajatpillai** [jkomyno/react-native-user-inactivity#6] opened 2018-09-13 09:02 UTC
The issue is that if **UserInactivity**  is triggered with a 10min time interval and if we want to change the interval in middle to 1min then what happens is first it will work for 10 min as it was triggered first and once the process is completed then only it will work for 1 min so, is there any way through which we can reset the time interval.

**Comment by jkomyno** [comment] 2018-09-29 09:30
Hi, I can't reproduce your issue with the newest version of `react-native-user-inactivity@0.1.1-next`. Can you please try out the following example? The value of the interval is bound to the value of the TextInput component, and if I set it from 50000ms to 50ms, the interval change is immediate.
https://snack.expo.io/H1rlra2FX

**Comment by jkomyno** [comment] 2018-10-19 14:45
@rajatpillai Hi there, any news on this?

**Comment by jkomyno** [comment] 2019-04-05 15:05
Closed as no one replied.

**Closed by jkomyno** 2019-04-05 15:05 UTC
